config/routes.rb
Rails.application.routes.draw do

  resources :tasks, except: :show do
    member do
      put :change
    end
  end
  
  devise_for :users

  root 'pages#home'

  get 'about' => 'pages#about'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  scope :to_do, -> { where(state: "to_do") }
  scope :doing, -> { where(state: "doing") }
  scope :done, -> { where(state: "done") }

  auto_html_for :content do
    html_escape
    image
    youtube(:width => "100%", :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  validates :user_id, presence: true
  validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to tasks_url if current_user
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :change]
  before_action :authenticate_user!

  def index
    @to_do = current_user.tasks.to_do
    @doing = current_user.tasks.doing
    @done = current_user.tasks.done
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html {redirect_to tasks_path, notice: "Task state was successfully updated."}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }
  BOOTSTRAP_FLASH_ICON = {
    success: 'glyphicon-ok',
    error: 'glyphicon-remove',
    alert: 'glyphicon-hand-up',
    notice: 'glyphicon-info-sign'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def icon_class_for(flash_type)
    BOOTSTRAP_FLASH_ICON.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def flash_messages(opts = {})
    html = ""
    flash.each do |msg_type, message|
      html << content_tag(:div, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
                concat content_tag(:span, "", class: "glyphicon #{icon_class_for(msg_type)}")
                concat content_tag(:span, message, class: "message")
              end
    end
    html.html_safe
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def state_links(task)
    case task.state
    when "to_do"
      link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-block btn-info"
    when "doing"
      html =  content_tag(:div, class: "btn-group btn-group-justified") do
                concat link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, class: "btn btn-info"
                concat link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-info"
              end
      html.html_safe
    when "done"
      link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-block btn-info"
    end
  end

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#bs-example-navbar-collapse-1"}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      = link_to root_path, class: "navbar-brand" do
        %i.fa.fa-circle-o-notch 
        Stukdo

      - if current_user
        = link_to new_task_path, class: "btn btn-primary navbar-btn pull-left" do
          %i.fa.fa-plus
          create task

    .collapse.navbar-collapse#bs-example-navbar-collapse-1      
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "About", about_path
          %li= link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Stukdo'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Stukdo'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .container
      = flash_messages
      = yield

app/views/pages/about.html.haml
.page-header
  %h1
    %i.fa.fa-circle-o-notch 
    Stukdo
%p This is simple Ruby on Rails Application for managing your ToDo list.
%p
  It is based on "Ruby On Rails Fundamentals" course by 
  = link_to "stuk.io.", "https://stuk.io"
  You can check source on
  = link_to "GitHub.", "https://github.com/sasa-friedrich-bitlab/stukdo"
%p
  You can sign up for free and test it.
%br
=link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg", role: "button"

app/views/pages/home.html.haml
.jumbotron.frontpage
  %h1
    %i.fa.fa-circle-o-notch 
    Stukdo
  %p Simple Ruby on Rails Application for managing your ToDo list.
  %br
  %br
  =link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg", role: "button"

app/views/tasks/_form.html.haml
= simple_form_for(@task) do |f|
  = f.error_notification

  = f.input :content, label: false, required: true, autofocus: true, placeholder: "Content...", input_html: { rows: "10" }

  = link_to 'Cancel', tasks_path, class: "btn btn-default"
  = f.button :submit, class: "btn btn-primary pull-right"

app/views/tasks/_task.html.haml
.panel.panel-info
  .panel-heading
    = link_to "created #{time_ago_in_words(task.created_at)} ago", edit_task_path(task)
    = link_to task_path(task), method: :delete, data: {confirm: "Are you sure?"}, class: "pull-right" do
      %i.fa.fa-remove
  .panel-body
    = task.content_html
  .panel-footer
    = state_links(task)

app/views/tasks/edit.html.haml
.page-header
  %h1 Editing Task

= render 'form'

app/views/tasks/index.html.haml
.row
  .col-md-4
    .page-header.text-center
      %h1 To do
    =render @to_do
  .col-md-4
    .page-header.text-center
      %h1 Doing
    =render @doing
  .col-md-4
    .page-header.text-center
      %h1 Done
    =render @done

app/views/tasks/new.html.haml
.page-header
  %h1 New Task

= render 'form'